// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Card: typeof import('./src/components/card/card.vue')['default']
    Clock: typeof import('./src/components/clock/index.vue')['default']
    LogErrorMsg: typeof import('./src/components/log-message/log-error-msg.vue')['default']
    LogState: typeof import('./src/components/logs-info/log-state.vue')['default']
    LogStateChart: typeof import('./src/components/charts/log-state-stats/log-state-chart.vue')['default']
    LogTimeChart: typeof import('./src/components/charts/log-time-stats/log-time-chart.vue')['default']
    MenuIcon: typeof import('./src/components/menu/menu-icon.vue')['default']
    MenuItem: typeof import('./src/components/menu/menu-item.vue')['default']
    ParseTabs: typeof import('./src/components/parse-tabs/index.vue')['default']
    PickDate: typeof import('./src/components/pick-date/index.vue')['default']
    PnCard: typeof import('./src/components/pn-card/index.vue')['default']
    RecentlyErrCard: typeof import('./src/components/recently-err-card/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunTimeline: typeof import('./src/components/run-timeline/index.vue')['default']
    RunTimelineItem: typeof import('./src/components/run-timeline/run-timeline-item.vue')['default']
    RunTlItemIcon: typeof import('./src/components/run-timeline/run-tl-item-icon.vue')['default']
    StateIcon: typeof import('./src/components/logs-info/state-icon.vue')['default']
  }
}
