codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
        base: auto
        if_ci_failed: error
        branches:
          - 'main'
    patch: false

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  branches:
    - 'main'
