name: CI Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: to app
        run: cd app

      - name: Run
        run: yarn dev

      - name: Report coverage
        uses: codecov/codecov-action@v2
