name: CI Action

on: [push, pull_request]

jobs:
  app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: PrintPwd
        run: echo $PWD

      - name: 📥 install
        uses: ./.github/actions/yarn-nm-install

      - name: See Yarn Ver
        run: yarn -v

      - name: Install Dep
        run: yarn

      - name: Run
        run: yarn dev

      - name: Report coverage
        uses: codecov/codecov-action@v2
